# Generated by Django 2.1.5 on 2019-01-24 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 15, 31, 0, 514919), verbose_name='date published'),
        ),
    ]
